// This file is auto-generated by @hey-api/openapi-ts

export const $AddAgentToChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        agentName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $AddOrchestratorToChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        orchestratorName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $AgentInfo = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        selfDescription: {
            type: 'string',
            nullable: true
        },
        isHuman: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const $ChannelInfo = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        members: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AgentInfo'
            },
            nullable: true
        },
        orchestrators: {
            type: 'array',
            items: {
                type: 'string'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $ChatMsg = {
    type: 'object',
    properties: {
        from: {
            type: 'string',
            nullable: true
        },
        created: {
            type: 'string',
            format: 'date-time'
        },
        parts: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ChatMsgPart'
            },
            nullable: true
        },
        id: {
            type: 'integer',
            format: 'int64'
        }
    },
    additionalProperties: false
} as const;

export const $ChatMsgPart = {
    type: 'object',
    properties: {
        textPart: {
            type: 'string',
            nullable: true
        },
        imageData: {
            type: 'string',
            format: 'byte',
            nullable: true
        },
        imageUrl: {
            type: 'string',
            format: 'uri',
            nullable: true
        },
        mimeType: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $CloneChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        newChannelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $CreateChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $DeleteChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $EditChannelNameRequest = {
    type: 'object',
    properties: {
        oldChannelName: {
            type: 'string',
            nullable: true
        },
        newChannelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $EditTextMessageRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        messageId: {
            type: 'integer',
            format: 'int64'
        },
        newText: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $GenerateNextReplyRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        chatMsgs: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ChatMsg'
            },
            nullable: true
        },
        candidates: {
            type: 'array',
            items: {
                type: 'string'
            },
            nullable: true
        },
        orchestrator: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $GenerateNextReplyResponse = {
    type: 'object',
    properties: {
        message: {
            '$ref': '#/components/schemas/ChatMsg'
        }
    },
    additionalProperties: false
} as const;

export const $GetChannelChatHistoryRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        count: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const $GetChannelMembersRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $JoinChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        createIfNotExists: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const $LeaveChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $RemoveAgentFromChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        agentName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $RemoveOrchestratorFromChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        orchestratorName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $SendTextMessageToChannelRequest = {
    type: 'object',
    properties: {
        channelName: {
            type: 'string',
            nullable: true
        },
        message: {
            '$ref': '#/components/schemas/ChatMsg'
        }
    },
    additionalProperties: false
} as const;